insert into genre(id, name) values (1, '액션');
insert into genre(id, name) values (2, 'SF');
insert into genre(id, name) values (3, '코미디');
insert into genre(id, name) values (4, '스릴러');
insert into genre(id, name) values (5, '전쟁');
insert into genre(id, name) values (6, '스포츠');
insert into genre(id, name) values (7, '뮤지컬');
insert into genre(id, name) values (8, '멜로');
insert into genre(id, name) values (9, '범죄');
